import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import Characters from "../components/Characters";
import { Layout } from "../components/Layout";
import { NavBar } from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar/>
        <h1>
          React Query with Next JS
        </h1>
      </main>
    </>
  );
}
